export default {
    id: '2025-2nd',
    meetings: [
        { date: '2025-09-05', presenter: 'Seungwoo Ahn', article: { title: 'Deriving the Coronal Separatrix-Web With the WSA Model', url: 'https://khu-ac.zoom.us/rec/share/qp20uyAAAEm6yhlSZ7I2fYyFU-zp34cmUZHcJ_lTUp1Xzjc3H9Dr88_BRlODxKRk.2UsfUsAM9pffhZ4Z' }, video: 'https://khu-ac.zoom.us/rec/share/IXl9pOSfKRLkY-YvHzBOdWu8gVL-ofMn-eexgTa8V0Ieo8v9iitZNLc1vzPVtGqj._osq8XWJSXSgM86N', ppt: 'TBD' },
        { date: '2025-09-12', presenter: 'Yeonwoo Jang', article: { title: 'Computation of Winding-Based Magnetic Helicity and Magnetic Winding Density for SHARP Magnetograms in Spherical Coordinates', url: 'https://link.springer.com/article/10.1007/s11207-023-02211-9' }, video: 'https://khu-ac.zoom.us/rec/share/PJUAxfIjI3jHt_1k2Yydp_LVERKE7U7qd4y5TlnrZyDzeNGPQ4Y71N1VWHskUPlP.hCl_WzNeIHONMNsV', ppt: 'TBD' },
        { date: '2025-10-24', presenter: 'Youngjae Kim', article: { title: 'The origin of interplanetary switchbacks in reconnection at chromospheric network boundaries', url: 'https://www.nature.com/articles/s41550-024-02321-9' }, video: 'https://khu-ac.zoom.us/rec/share/N-D9Ce0csx9Bp4-MFgRivoV6zEYktPb_U1Mu6gQWVFHsTfHN9SAyESEOAWzz-ifr.C0Q-_OEAJiYAZurH', ppt: 'TBD' },
        { date: '2025-11-07', presenter: 'Sibaek Yi', article: { title: 'MHD modelling of the near-sun evolution of coronal mass ejection initiated from a sheared arcade', url: 'https://doi.org/10.1093/mnras/staf307' }, video: 'https://khu-ac.zoom.us/rec/share/rrNxe7vvzdj2V3jIGYdVBx_p-XkWzmPaTd3Kr0fp04JBgF9Zx4J6WmdVfTA4oPUW.aO41iN0ziRPaOVSC', ppt: 'TBD' },
        { date: '2025-11-14', presenter: 'Daeil Kim', article: { title: 'Current Helicity in Response to Coronal Mass Ejections', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/adf18b' }, video: 'https://khu-ac.zoom.us/rec/share/rRV2Qd20uBsOdpHWmy1zzosabAhLU9-70C22A5TYo8NPgy57RzAkMcTtUQ0V7uQT.JLlDi5IvjYaWSUqX', ppt: 'TBD' },
        { date: '2025-11-21', presenter: 'Junmo An', article: { title: 'What Determines the Brightness of the Magnetically Open Solar Corona?: Insights from Three-dimensional Radiative Magnetohydrodynamic Simulations and Observations', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/ae0468' }, video: 'https://khu-ac.zoom.us/rec/share/9Dlom6xYgkFUpJWHefyNrMMivqWUJMfJ1FdlHemvmxTqJJ5xdjsvOJ5RGyXSE_oV.OG-oKkfdSNYBkFmf', ppt: 'TBD' },
        { date: '2025-11-28', presenter: 'Donghui Son', article: { title: 'EXTENSION OF THE MURAM RADIATIVE MHD CODE FOR CORONAL SIMULATIONS', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/834/1/10' }, video: 'https://khu-ac.zoom.us/rec/share/HWPUFPMSqqbsum-phY0OLrj53rCUFru4loFroQ8U1wIbU1WHTotmSIFrxX1Q3SaJ.Zwo2xr4_8Cr87fYw', ppt: 'TBD' },
        { date: '2025-12-12', presenter: 'Junmu Youn', article: { title: 'Fine Structures of Tiny Quiet Sun Jets Observed by Solar Orbiter and Big Bear Solar Observatory', url: 'https://iopscience.iop.org/article/10.3847/2041-8213/ae0df2' }, video: 'https://khu-ac.zoom.us/rec/share/2vCNRYhWlEn5A3txcaFuv3VLLqfeM9s0aLFSWzHJo20t52L4UZVRknnmuBgTW-y1.aW7wPUXF1a8CDGfj', ppt: 'TBD' },
        { date: '2025-12-19', presenter: 'Sangjin Park', article: { title: 'Solar Overshoot Region and Small-scale Dynamo with Realistic Energy Flux', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/aa784b' }, video: 'https://khu-ac.zoom.us/rec/share/vq4EjEKiKnNBRarb6zMMX3j50766N4meuad3uQJ3BSSEfDhVtSHA_z1yIc_yYMlS.Rtuqp5L1OwjxaklF', ppt: 'TBD' },
        { date: '2026-01-09', presenter: 'Mingyu Jeon', article: { title: 'Numerical Simulations of Flare-productive Active Regions: δ-sunspots, Sheared Polarity Inversion Lines, Energy Storage, and Predictions', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/aa95c2/meta' }, video: 'https://khu-ac.zoom.us/rec/share/lIC25YJXJ3Uz_SW-zKBCZXDJWZCzuDVmLSWiVCzAEWuG81UzsyhjWe-SoM92OPEt.ytFvTa9LU88bPIyF', ppt: 'TBD' }
    ]
};
