export default {
    id: '2025-1st',
    meetings: [
        { date: '2025-02-14', presenter: 'Daeil Kim', article: { title: 'Studying the Spheromak Rotation in Data-constrained Coronal Mass Ejection Modeling with EUHFORIA and Assessing Its Effect on the Bz Prediction', url: 'https://iopscience.iop.org/article/10.3847/1538-4365/ad0df4' }, video: 'https://khu-ac.zoom.us/rec/share/IXl9pOSfKRLkY-YvHzBOdWu8gVL-ofMn-eexgTa8V0Ieo8v9iitZNLc1vzPVtGqj._osq8XWJSXSgM86N', ppt: 'TBD' },
        { date: '2025-02-21', presenter: 'Junmu Youn', article: { title: 'The Coronal Veil', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/ac3df9' }, video: 'https://khu-ac.zoom.us/rec/share/zwH2H4Gkt_ct3swucDxhegoliKYN2qBNuHojRjTAcb6WciGVEZTZkW7Vv8i0Tm4.QUJVczMCFVgOxvwN', ppt: 'TBD' },
        { date: '2025-02-28', presenter: 'Yeongmin Kang', article: { title: 'Data-driven MHD Simulation of the Formation of a Magnetic Flux Rope and an Inclined Solar Eruption', url: 'https://doi.org/10.3847/1538-4357/ad6a54' }, video: 'https://khu-ac.zoom.us/rec/share/G20O-BFdsYKLlnRUIoJ2xdjzoDZiUBSRrxmJDyQyI43gyg-Z6cSYIwUNeGU6jJn-._B1qVeDdkKROF17g', ppt: 'TBD' },
        {
            date: '2025-03-07', presenter: 'Sangjin Park', articles: [
                { title: 'Penumbral fine structure and driving mechanisms of large-scale flows in simulated sunspots', url: 'https://iopscience.iop.org/article/10.1088/0004-637X/729/1/5' },
                { title: 'NUMERICAL SUNSPOT MODELS: ROBUSTNESS OF PHOTOSPHERIC VELOCITY AND MAGNETIC FIELD STRUCTURE', url: 'https://iopscience.iop.org/article/10.1088/0004-637X/750/1/62' }
            ], video: 'https://khu-ac.zoom.us/rec/share/JP_JBwn2rXzXxqVRnyAJf9WEp3pSA3MAdPDzOXCJrGM6ea4lGdfLJ4VSZ4gCdoXd.XMYkZSGqfee5uwRg', ppt: 'TBD'
        },
        { date: '2025-03-14', presenter: 'Kyungsun Park', article: { title: 'Multispecies and Multifluid MHD Approaches for the Study of Ionospheric Escape at Mars', url: 'https://doi.org/10.1029/2017JA025117' }, video: 'https://khu-ac.zoom.us/rec/share/0P7irjW7v7Bpd3SlCi7ZhEQSCzbWGL_C56usbjBoevSU8QOvEVD-B9QSDiHLNDrm.q5Byp7l9EQvq7EMn', ppt: 'TBD' },
        { date: '2025-03-21', presenter: 'Youngjae Kim', article: { title: 'Applying the Weighted Horizontal Magnetic Gradient Method to a Simulated Flaring Active Region', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/aab891/meta' }, video: 'https://khu-ac.zoom.us/rec/share/vU-Ur-HXGsMj6ooe09QG0gJv_XF1va7xKl70Lnf-zCE0PkCGzVL4LizdJUfFriZg.8e63ke1abtdJgqun', ppt: 'TBD' },
        { date: '2025-03-28', presenter: 'Sibaek Yi', article: { title: 'A Data-constrained Model for Coronal Mass Ejections Using the Graduated Cylindrical Shell Method', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/aad3b4/meta' }, video: 'https://khu-ac.zoom.us/rec/share/mBCZNlhl2EDsr8KNl-BUFx8lSQpy5IF1JE9tpuvaVn1JxnJaG6VafFfhvApxXX_Z.w5DZwUCOf9K7Y3sS', ppt: 'TBD' },
        { date: '2025-04-04', presenter: 'Donghui Son', article: { title: 'Convective Magnetic Flux Emergence Simulations from the Deep Solar Interior to the Photosphere: Comprehensive Study of Flux Tube Twist', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/ad7e1d' }, video: 'https://khu-ac.zoom.us/rec/share/oCjZN6pEldM7-yoKhkpUjXwbymMK1wOSjoLXcbit--Cvpmsfhfu7mQzGtHDYatw3.oFWSlNMsIaUJ0YQR', ppt: 'TBD' },
        { date: '2025-05-16', presenter: 'Mingyu Jeon', article: { title: 'Models and data analysis tools for the Solar Orbiter mission', url: 'https://www.aanda.org/articles/aa/full_html/2020/10/aa35305-19/aa35305-19.html' }, video: 'https://khu-ac.zoom.us/rec/share/VjuvVJkxQ8jKqlwC3sK8ode_4Ksce8h7WJfXncRaDrh8ejTaYReLUCv3_P0Nf-5Y.7hsYCO86pTOKDUS2', ppt: 'TBD' },
        { date: '2025-05-23', presenter: 'Junmo An', article: { title: 'Which Component of Solar Magnetic Field Drives the Evolution of Interplanetary Magnetic Field over the Solar Cycle?', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/acd053' }, video: 'https://khu-ac.zoom.us/rec/share/OFAfjfu7XqbZd6AJJA8P2uiQTQQ7LuIyKWiwHH27fz80NxesAAjKc4-JVNYlY2nr.WNGhrqPr87Xf6Rbe', ppt: 'TBD' },
        { date: '2025-06-13', presenter: 'Yeonwoo Jang', article: { title: 'Solar Eruptions Triggered by Flux Emergence below or near a Coronal Flux Rope', url: 'https://iopscience.iop.org/article/10.3847/1538-4357/ad1826' }, video: 'https://khu-ac.zoom.us/rec/share/nXjCpDdkOqshqFJ_kQsd27b7aqPlDROQ8hsl9I1tXPze36RojtLg-YSJvpsJg88f.IjZnNtbnsvwCBrcN', ppt: 'TBD' },
        { date: '2025-06-20', presenter: 'Jihye Kang', article: { title: 'The role of the external toroidal magnetic field on the large-angle rotation of magnetic flux ropes', url: 'https://www.aanda.org/articles/aa/full_html/2025/03/aa51543-24/aa51543-24.html' }, video: 'https://khu-ac.zoom.us/rec/share/enUtuEwwgq-PIG8IZ6_NQz-tsHsRgh6VIR9zl8FL6XEXgc6kWJobtROmUaB_OPBk.K-3iY6hTJ6yaqlar', ppt: 'TBD' }
    ]
};
